const hyper = ["Let us assume you met a rudimentary magician. Let us assume he can do five simple tricks--he can pull a rabbit out of his hat, he can make a coin disappear, he can turn the ace of spades into the Joker card, and two others in a similar vein. These are his only tricks and he can't learn anymore; he can only do these five. HOWEVER, it turns out he's doing these five tricks with real magic. It's not an illusion; he can actually conjure the bunny out of the ether and he can move the coin through space. He's legitimately magical, but extremely limited in scope and influence. Would this person be more impressive than Albert Einstein?", "Let us assume a fully grown, completely healthy Clydesdale horse has his hooves shackled to the ground while his head is held in place with thick rope. He is conscious and standing upright, but completely immobile. And let us assume that--for some reason--every political prisoner on earth will be released from captivity if you can kick this horse to death in less than twenty minutes. You are allowed to wear steel-toed boots. Would you attempt to do this?", "Let us assume there are two boxes on a table. In one box, there is a relatively normal turtle; in the other, Adolf Hitler's skull. You have to select one of these items for your home. If you select the turtle, you can't give it away and you have to keep it alive for two years; if either of these parameters are not met, you will be fined $999 by the state. If you select Hitler's skull, you are required to display it in a semi-prominent location in your living room for the same amount of time, although you will be paid a stipend of $120 per month for doing so. Display of the skull must be apolitical. Which option do you select?", "At long last, someone invents 'the dream VCR'. This machine allows you to tape an entire evening's worth of your own dreams, which you can then watch at your leisure. However, the inventor of the dream VCR will only allow you to use this device of you agree to a strange caveat: When you watch your dreams, you must do so with your family and your closest friends in the same room. They get to watch your dreams along with you. And if you don't agree to this, you can't use the dream VCR. Would you still do this?"];

const hyper2 = ["Defying all expectation, a group of Scottish marine biologists capture a live Loch Ness Monster. In an almost unbelievable coincidence, a bear hunter in the Pacific Northwest shoots a Sasquatch in the thigh, thereby allowing zoologists to take the furry monster into captivity. These events happen on the same afternoon. That evening, the president announces he may have thyroid cancer and will undergo a biopsy later that week. You are the front page editor of The New York Times: What do you play as the biggest story?", "You meet the perfect person. Romantically, this person is ideal: You find them physically attractive, intellectually stimulating, consistently funny, and deeply compassionate. However, they have one quirk: This individual is obsessed with Jim Henson's gothic puppet fantasy The Dark Crystal. Beyond watching it on DVD at least once a month, he/she peppers casual conversation with Dark Crystal references, uses Dark Crystal analogies to explain everyday events, and occasionally likes to talk intensely about the film's 'deeper philosophy.' Would this be enough to stop you from marrying this individual?", "You meet a wizard in downtown Chicago. The wizard tells you he can make you more attractive if you pay him money. When you ask how this process works, the wizard points to a random person on the street. You look at this random stranger. The wizard says, 'I will now make them a dollar more attractive.' He waves his magic wand. Ostensibly, this person does not change at all; as far as you can tell, nothing is different. But--somehow--this person is suddenly a little more appealing. The tangible difference is invisible to the naked eye, but you can't deny that this person is vaguely sexier. This wizard has a weird rule, though--you can only pay him once. You can't keep giving him money until you're satisfied. You can only pay him one lump sum up front. How much cash do you give the wizard?", "Every person you have ever slept with is invited to a banquet where you are the guest of honor. No one will be in attendance except you, the collection of your former lovers, and the catering service. After the meal, you are asked to give a fifteen-minute speech to the assembly. What do you talk about?"];

const hyper3 = ["You have a brain tumor. Though there is no discomfort at the moment, this tumor would unquestionably kill you in six months. However, your life can (and will) be saved by an operation; the only downside is that there will be a brutal incision to your frontal lobe. After the surgery, you will be significantly less intelligent. You will still be a fully functioning adult, but you will be less logical, you will have a terrible memory, and you will have little ability to understand complex concepts or difficult ideas. The surgery is in two weeks. How do you spend the next fourteen days?", "You are sitting in an empty bar (in a town you’ve never before visited), drinking Bacardi with a soft-spoken acquaintance you barely know. After an hour, a third individual walks into the tavern and sits by himself, and you ask your acquaintance who the new man is. “Be careful of that guy,” you are told. “He is a man with a past.” A few minutes later, a fourth person enters the bar; he also sits alone. You ask your acquaintance who this new individual is. “Be careful of that guy, too,” he says. “He is a man with no past.” Which of these two people do you trust less?", "You have won a prize. The prize has two options, and you can choose either (but not both). The first option is a year in Europe with a monthly stipend of $2,000. The second option is ten minutes on the moon. Which option do you select?", "Your best friend is taking a nap on the floor of your living room. Suddenly, you are faced with a bizarre existential problem: This friend is going to die unless you kick them (as hard as you can) in the rib cage. If you don’t kick them while they slumber, they will never wake up. However, you can never explain this to your friend; if you later inform them that you did this to save their life, they will also die from that. So you have to kick a sleeping friend in the ribs, and you can’t tell them why. Since you cannot tell your friend the truth, what excuse will you fabricate to explain this (seemingly inexplicable) attack?"];

const hyper4 = ["For whatever the reason, two unauthorized movies are made about your life. The first is an independently released documentary, primarily comprised of interviews with people who know you and bootleg footage from your actual life. Critics are describing the documentary as “brutally honest and relentlessly fair.” Meanwhile, Columbia Tri-Star has produced a big-budget biopic of your life, casting major Hollywood stars as you and all your acquaintances; though the movie is based on actual events, screenwriters have taken some liberties with the facts. Critics are split on the artistic merits of this fictionalized account, but audiences love it. Which film would you be most interested in seeing?"];


function random() {
    let ran1 = hyper[Math.floor(Math.random()* hyper.length)];
let ran2 = hyper2[Math.floor(Math.random()* hyper2.length)];
let ran3 = hyper2[Math.floor(Math.random()* hyper3.length)];
let ran4= hyper2[Math.floor(Math.random()* hyper4.length)];

let query = [`${ran1}`, `${ran2}`, `${ran3}`, `${ran4}`]
let final = query[Math.floor(Math.random()*query.length)]

    document.getElementById('hyperthet').innerHTML = `${final}`;
}
